# Generated by Django 6.0.2 on 2026-02-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartnotes', '0002_note_user_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
